-- AlterTable
ALTER TABLE `account` ADD COLUMN `maxDriver` INTEGER NOT NULL DEFAULT 7,
    ADD COLUMN `maxVehicle` INTEGER NOT NULL DEFAULT 7,
    ADD COLUMN `maxVehicleFleet` INTEGER NOT NULL DEFAULT 1,
    MODIFY `plan` ENUM('FREE', 'BASIC', 'ADVANCED', 'CUSTOM') NOT NULL DEFAULT 'FREE';
